INSERT INTO api_departamento (id, departamento) VALUES (1, 'LA LIBERTAD');
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (1, 'ASCOPE', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (1, 'PAIJAN', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (2, 'CASA GRANDE', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (3, 'CHICAMA', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (4, 'ASCOPE', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (5, 'SANTIAGO DE CAO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (6, 'RAZURI', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (7, 'MAGDALENA DE CAO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (8, 'CHOCOPE', 1);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (2, 'BOLIVAR', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (9, 'BOLIVAR', 2);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (10, 'UCUNCHA', 2);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (11, 'BAMBAMARCA', 2);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (12, 'UCHUMARCA', 2);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (13, 'LONGOTEA', 2);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (14, 'CONDORMARCA', 2);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (3, 'CHEPEN', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (15, 'CHEPEN', 3);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (16, 'PACANGA', 3);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (17, 'PUEBLO NUEVO', 3);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (4, 'GRAN CHIMU', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (18, 'LUCMA', 4);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (19, 'MARMOT', 4);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (20, 'CASCAS', 4);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (21, 'SAYAPULLO', 4);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (5, 'JULCAN', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (22, 'HUASO', 5);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (23, 'CALAMARCA', 5);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (24, 'CARABAMBA', 5);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (25, 'JULCAN', 5);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (6, 'OTUZCO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (26, 'SINSICAP', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (27, 'SALPO', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (28, 'CHARAT', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (29, 'MACHE', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (30, 'HUARANCHAL', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (31, 'LA CUESTA', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (32, 'OTUZCO', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (33, 'PARANDAY', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (34, 'AGALLPAMPA', 6);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (35, 'USQUIL', 6);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (7, 'PACASMAYO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (36, 'PACASMAYO', 7);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (37, 'JEQUETEPEQUE', 7);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (38, 'GUADALUPE', 7);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (39, 'SAN PEDRO DE LLOC', 7);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (40, 'SAN JOSE', 7);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (8, 'PATAZ', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (41, 'ONGON', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (42, 'HUAYO', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (43, 'CHILLIA', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (44, 'HUANCASPATA', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (45, 'TAURIJA', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (46, 'URPAY', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (47, 'TAYABAMBA', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (48, 'SANTIAGO DE CHALLAS', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (49, 'HUAYLILLAS', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (50, 'BULDIBUYO', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (51, 'PIAS', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (52, 'PARCOY', 8);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (53, 'PATAZ', 8);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (9, 'SANCHEZ CARRION', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (54, 'SARTIMBAMBA', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (55, 'HUAMACHUCO', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (56, 'SANAGORAN', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (57, 'SARIN', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (58, 'CURGOS', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (59, 'MARCABAL', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (60, 'CHUGAY', 9);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (61, 'COCHORCO', 9);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (10, 'SANTIAGO DE CHUCO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (62, 'SANTA CRUZ DE CHUCA', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (63, 'SITABAMBA', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (64, 'MOLLEBAMBA', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (65, 'CACHICADAN', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (66, 'SANTIAGO DE CHUCO', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (67, 'QUIRUVILCA', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (68, 'ANGASMARCA', 10);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (69, 'MOLLEPATA', 10);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (11, 'TRUJILLO', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (70, 'HUANCHACO', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (71, 'SIMBAL', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (72, 'SALAVERRY', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (73, 'FLORENCIA DE MORA', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (74, 'MOCHE', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (75, 'EL PORVENIR', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (76, 'VICTOR LARCO HERRERA', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (77, 'POROTO', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (78, 'LAREDO', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (79, 'TRUJILLO', 11);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (80, 'LA ESPERANZA', 11);
INSERT INTO api_provincia (id, provincia, departamento_id) VALUES (12, 'VIRU', 1);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (81, 'GUADALUPITO', 12);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (82, 'VIRU', 12);
INSERT INTO api_distrito (id, distrito, provincia_id) VALUES (83, 'CHAO', 12);